import java.util.Random;
import java.util.Scanner;

public class Task1Try4 {
    public static void main(String args[]){

        Scanner s=new Scanner(System.in);
        Random r= new Random();
        int score=0;
        int round=0;

        System.out.println("Welcome to the number guessing game!");
        System.out.println("****Rules****");
        System.out.println("1]You've to guess the number generated by the computer(Between 1 and 100)");
        System.out.println("2]Each round will consist of 5 attempts.");
        System.out.println("3]If you can guess the correct number within 5 attempts you win the round else you lose.");
        System.out.println("4]You can choose to guess again or play another round with a different number.");
        System.out.println("5]Your score will be calculated based on the number of guesses you took to get the correct guess.");

        do{
            int randomNumber=r.nextInt(101)+1;
            int attempts=0;
            boolean CorrectGuess=false;

            System.out.println("Round "+(round+1)); 
            
            int MaxAttempts=5;
            do{
            while(attempts<MaxAttempts){
                System.out.println("Guess the number between 1 and 100");
                int Guess=s.nextInt();
                attempts++;

                if(Guess==randomNumber){
                    CorrectGuess=true;
                    break;
                }
                else if(Guess>randomNumber){
                    System.out.println("Too high");
                }
                else if(Guess<randomNumber){
                    System.out.println("Too low");
                }else{
                    System.out.println("Invalid input");
                }

            }
            if(CorrectGuess){
                System.out.println("Bravo! You guessed the number in "+attempts+" attempts");
                score+=attempts;
                break;
            }else{
                    System.out.println("Sorry you've reached the maximun number of attempts");
                    System.out.println("Would you like to guess again?(yes/no)");
                    String guessAgain=s.next().toLowerCase();
                    while(!(guessAgain.equals("yes")||guessAgain.equals("no"))){
                        System.out.println("Invalid input! Please write yes/no");
                        guessAgain=s.next().toLowerCase();
                    }
                    if(guessAgain.equals("yes")){
                        MaxAttempts+=5;
                    }
                    else {
                        break;
                    }
            }
            }while(true);
            System.out.println("The random number was "+randomNumber);
            System.out.println("Would you like to play again?(yes/no)");
            String playAgain=s.next().toLowerCase();
            while(!(playAgain.equals("yes")||playAgain.equals("no"))){
                System.out.println("Invalid input! Please write yes/no");
                playAgain=s.next().toLowerCase();
            }
            if(playAgain.equals("yes")){
                round++;
            }else{
               
                break;
            }
        }while(true);
        System.out.println("Thankyou for playing");
        System.out.println("Your score: You gave "+score+" guesses");
        s.close();
    }

            }

